name 'osmc'
maintainer 'Peter Rifel'
maintainer_email 'pgrifel@gmail.com'
license 'all_rights'
source_url 'https://github.com/rifelpet/osmc-cookbook'
issues_url 'https://github.com/rifelpet/osmc-cookbook/issues'
description 'Installs/Configures OSMC on my raspberry pi'
long_description 'Installs/Configures OSMC on my raspberry pi'
version '0.1.0'
